#@ load("@ytt:data", "data")
#! This if condition ensures that this Java Tekton pipeline is only created if the supply chain is testing or testing_scanning, and the TAP profile used is full, iterate or build.
#@ if/end data.value.type == 'dev':
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  name: postgresql-claim
spec:
  classRef:
    name: postgresql-unmanaged
  parameters:
    storageGB: 5
